{% set name = "napari-threedee" %}
{% set version = "0.0.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c6e9f9262e2c627473b15dc8de615549b1b4cdbf14744659b5eda5ffe5446c6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - einops
    # - igl # feedstock currently abandoned
    - magicgui
    - napari
    - numpy
    - pandas
    - pydantic
    - psygnal
    - qtpy
    - scipy
    - superqt
    - vispy
    - zarr
    - morphosamplers

test:
  imports:
    - napari_threedee
  # commands:
  # pip check fails to recognize igl as libigl
  #  - pip check
  requires:
    - pyqt
  #  - pip
    - python {{ python_min }}

about:
  home: https://github.com/alisterburt/napari-threedee
  summary: A suite of useful tools based on 3D interactivity in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kevinyamauchi
    - alisterburt
    - psobolewskiPhD
