{% set name = "napari-threedee" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-threedee-{{ version }}.tar.gz
  sha256: f0bc7586e903a77714d823cd4344d839ed930d1b03e998f1964cea476f69a10a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - einops
    - npe2
    - napari
    - numpy
    - qtpy
    - morphosamplers

test:
  imports:
    - napari_threedee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisterburt/napari-threedee
  summary: A suite of useful tools based on 3D interactivity in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kevinyamauchi
    - alisterburt
